# Generated by Django 2.1.7 on 2019-03-15 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grades',
            fields=[
                ('gId', models.IntegerField(primary_key=True, serialize=False)),
                ('gNum', models.IntegerField()),
                ('gName', models.CharField(max_length=30)),
                ('gDate', models.DateTimeField()),
                ('gIsDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['gId'],
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sCreateTime', models.DateTimeField(auto_created=True)),
                ('sName', models.CharField(max_length=10)),
                ('sNum', models.IntegerField()),
                ('sGender', models.BooleanField()),
                ('sDate', models.DateTimeField()),
                ('sDelete', models.BooleanField(default=False)),
                ('sAlongTime', models.DateTimeField(auto_now=True)),
                ('sLastTime', models.DateTimeField(auto_now_add=True)),
                ('sGrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.grades')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['sDate'],
            },
        ),
    ]
